IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'DWH')
BEGIN
	ALTER DATABASE DWH SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE DWH;
END

CREATE DATABASE [DWH];
USE [DWH];

CREATE SCHEMA bronze;
CREATE SCHEMA staging;
CREATE SCHEMA gold;


